### ISSUE TITLE
test_logger_configuration is failing

### ISSUE THREAD

**Issue by ChihChengLiang** [ethereum/trinity#1347] opened 2019-12-03 17:58 UTC
### What is wrong?

After the fix of async runner in #1338, these tests turn out to be failing and were marked as `xfail`

https://github.com/ethereum/trinity/blob/0e3e67d2ceb52e124fcb866f11d3f9704cfe04bf/tests/integration/test_trinity_cli.py#L247-L270

### How can it be fixed

Need to investigate further

**Comment by cburgdorf** [comment] 2019-12-05 11:25
I wanted to understand this better and looked into it today. Here's a quick brain dump.

It seems that this is a regression that came with #1277 when the new logging was introduced that doesn't rely on `multiprocessing.Queue` anymore. It seems that the regression made it's way in because the `AsyncProcessRunner` had a bug where a test would sometimes automatically pass when the timeout of the test was hit. That bug was fixed by #1338 which now exposes this regression caused by #1277.

I wanted to prove that so I went back to an older commit and just cherry-picked the fix from #1388 to see if all the logging tests would still pass which is the case.

I tried to come up with a fix but couldn't find the root cause yet so I wanted to at least did a quick brain dump.

/cc @pipermerriam

**Comment by pipermerriam** [comment] 2019-12-05 18:28
Nothing immediately comes to mind.  I believe someone will just need to dig in and see where things aren't being correctly done.

Also, I think that it would be better if we could streamline how these are tested since the current mechanism is very indirect...

**Comment by gsalgado** [comment] 2020-05-18 08:40
ISTM that there's something wrong with the code responsible for capturing trinity's output and matching it against the expected/unexpected patterns. I say that because for `test_logger_configuration[command1,...]` we expect only to see `{'Started main process', '>>> ping'}` patterns, and in two subsequent runs, both containing the expected pattern, one failed and the other passed. http://sprunge.us/PS4BLy is the one that failed, and http://sprunge.us/uDdS1U is the one that passed

**Comment by gsalgado** [comment] 2020-05-18 08:54
And another clue that might lead us to to the buggy code is the fact that all tests that fail intermittently are the ones that have empty sets for one or more of the expected/unexpected patterns

**Closed** 2021-07-01 16:22 UTC
Labels: flaky-test, type: bug
