### ISSUE TITLE
Crash during fast sync

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#308] opened 2019-02-25 16:47 UTC
### What is wrong?

I'm pretty sure we already had this reported but I couldn't find it. This error is coming up *very* often during fast sync for me. 

```
126170: WARNING  02-24 23:14:07   FastChainBodySyncer  Task <coroutine object FastChainBodySyncer._launch_prerequisite_tasks at 0x7f4868d49830> finished unexpectedly: No header with hash 0xd50fcbd93c68d777d10c9e1033f001f2c9e6e1aa0137dbbf08021965297905a3 found
126171-   DEBUG  02-24 23:14:07   FastChainBodySyncer  Task failure traceback
126172-trinity._utils.mp.RemoteTraceback: 
126173-"""
126174-Traceback (most recent call last):
126175-  File "/home/ubuntu/trinity/venv/lib/python3.6/site-packages/eth/db/header.py", line 167, in _get_block_header_by_hash
126176-    header_rlp = db[block_hash]
126177-  File "/home/ubuntu/trinity/venv/lib/python3.6/site-packages/eth/db/backends/level.py", line 54, in __getitem__
126178-    raise KeyError(key)
126179-KeyError: b'\xd5\x0f\xcb\xd9<h\xd7w\xd1\x0c\x9e\x103\xf0\x01\xf2\xc9\xe6\xe1\xaa\x017\xdb\xbf\x08\x02\x19e)y\x05\xa3'
126180-
126181-During handling of the above exception, another exception occurred:
126182-
126183-Traceback (most recent call last):
126184-  File "/home/ubuntu/trinity/trinity/_utils/mp.py", line 68, in wrapper
126185-    return attr(*args, **kwargs)
126186-  File "/home/ubuntu/trinity/venv/lib/python3.6/site-packages/eth/db/header.py", line 156, in get_block_header_by_hash
126187-    return self._get_block_header_by_hash(self.db, block_hash)
126188-  File "/home/ubuntu/trinity/venv/lib/python3.6/site-packages/eth/db/header.py", line 170, in _get_block_header_by_hash
126189-    encode_hex(block_hash)))
126190-eth.exceptions.HeaderNotFound: No header with hash 0xd50fcbd93c68d777d10c9e1033f001f2c9e6e1aa0137dbbf08021965297905a3 found
126191-"""
126192-
126193-The above exception was the direct cause of the following exception:
126194-
126195-Traceback (most recent call last):
126196-  File "/home/ubuntu/trinity/p2p/service.py", line 139, in _run_task_wrapper
126197-    await awaitable
126198-  File "/home/ubuntu/trinity/p2p/service.py", line 158, in _run_daemon_task_wrapper
126199-    await awaitable
126200-  File "/home/ubuntu/trinity/trinity/sync/full/chain.py", line 465, in _launch_prerequisite_tasks
126201-    self.db.coro_get_block_header_by_hash(headers[0].parent_hash)
126202-  File "/home/ubuntu/trinity/p2p/cancellable.py", line 20, in wait
126203-    return await self.wait_first(awaitable, token=token, timeout=timeout)
126204-  File "/home/ubuntu/trinity/p2p/cancellable.py", line 42, in wait_first
126205-    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
126206-  File "/home/ubuntu/trinity/venv/lib/python3.6/site-packages/cancel_token/token.py", line 152, in cancellable_wait
126207-    return done.pop().result()
126208-  File "/home/ubuntu/trinity/trinity/_utils/mp.py", line 33, in method
126209-    args,
126210-  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
126211-    result = self.fn(*self.args, **self.kwargs)
126212-  File "/usr/lib/python3.6/multiprocessing/managers.py", line 772, in _callmethod
126213-    raise convert_to_error(kind, result)
126214-eth.exceptions.HeaderNotFound: No header with hash 0xd50fcbd93c68d777d10c9e1033f001f2c9e6e1aa0137dbbf08021965297905a3 found
```

### How can it be fixed

:sweat_smile:

**Comment by carver** [comment] 2019-02-26 20:00
Just before it crashes:
```
# If the parent header doesn't exist yet, this is a legit bug instead of a fork,
# let the HeaderNotFound exception bubble up
```
:sweat_smile: 
Taking a look now...

**Comment by lithp** [comment] 2019-02-26 23:22
@cburgdorf is there any chance you have a debug log from around when this happens? Jason and I tried to look into this but very unsure of what could be happening. The logs would show whether it was happening around the same time that the skeleton syncer switches peers.

**Comment by carver** [comment] 2019-02-26 23:31
Also, we unfortunately haven't been able to connect to any peers at the Consensys office, so can't reproduce it yet. I'm going to keep trying from home tonight. Either way, @cburgdorf can you try to reproduce with the extra logging in #321 ?

**Comment by lithp** [comment] 2019-02-27 00:09
@veox you seem to have also run into this error: https://gist.github.com/veox/22f44209bc6e5d8f1d486869e4ad9918#file-2-that-other-crash-py

Do you remember when it happened? Were you on master or did it occur when you were running https://github.com/ethereum/trinity/pull/236?

**Comment by lithp** [comment] 2019-02-27 00:37
We think it *might* have something to do with `OrderedTaskPrep`'s pruning. If that's correct then changing [`max_depth`](https://github.com/ethereum/trinity/blob/master/trinity/_utils/datastructures.py#L439) to something smaller (such as 10) should cause this problem to occur more often. Is there any chance you could try that and see what happens?

**Comment by lithp** [comment] 2019-02-27 00:46
@cburgdorf We think it *might* have something to do with `OrderedTaskPrep`'s pruning. If that's correct then changing [`max_depth`](https://github.com/ethereum/trinity/blob/master/trinity/_utils/datastructures.py#L439) to something smaller (such as 10) should cause this problem to occur more often. Is there any chance you could try that and see what happens?

The mechanism might be:
- The OTP in `FastChainBodySyncer` has a `ready_tasks` queue which is consumed by `_persist_ready_blocks`.
- OTP prunes away any tasks which are deeper than `max_depth` from the most recently registered task, even if the task is ready!
- If the header syncer sends headers which reference headers which haven't yet been persisted by `_persist_ready_blocks` but *have* been pruned by OTP, then this exception will be thrown.

**Comment by carver** [comment] 2019-02-27 06:49
I'm trying to reproduce it at home since peer discovery is broken on the Consensys guest wifi. Once I can reproduce the problem, I'll try it again with #327 to see how long it takes (if ever) to get it again. Anyone is welcome to join me in the same test :)

**Comment by cburgdorf** [comment] 2019-02-27 08:22
Here's a gist with two extra minutes before the crash. That's not with the extra logging yet.

https://gist.github.com/cburgdorf/9d2d8d6c585b366205a62810620eeef6

I'm going to put #327 to work first and see if that runs stable. Even if it runs stable I can still run the extra logging branch afterwards to give us more clarity.

**Comment by cburgdorf** [comment] 2019-02-27 12:22
After running #327 until it crashed (with a different but related error), I'm now putting #321 to work to see if we can get more info about the root cause.

**Comment by veox** [comment] 2019-02-27 13:16
@lithp 

> Were you on master or did it occur when you were running #236?

I haven't run `master` for a long while; I'm pretty sure it was the branch of PR #236.

**Comment by carver** [comment] 2019-02-27 16:03
Thanks @cburgdorf ! There was an `await` bug in #321 -- it's fixed now.

BTW, I was able to confirm that the header with the missing parent was at block number 38021 in the canonical chain, and the canonical head tip in the database was only 23184, so being related to pruning seems very plausible (since it prunes at 10k headers).

If you have the crash log for #327 that would be useful too. I'll also try to reproduce with that.

**Comment by cburgdorf** [comment] 2019-02-27 16:29
>There was an `await` bug in #321 -- it's fixed now.

Oh, then I may have to re-run? This is a log created from #321

https://gist.github.com/cburgdorf/f7477bc0ab29e9a7ea4fd1504b5bdd7c

>If you have the crash log for #327 that would be useful too.

That's this.
https://gist.github.com/cburgdorf/21587b5f8ad8bf57cc8defa723a4e42a

**Comment by carver** [comment] 2019-04-17 22:52
Currently, the plan is to skip implementing "standard fast sync" altogether. So I'm going to close as wontfix, until that changes.

Will reopen if #511 is reversed.

**Closed by carver** 2019-04-17 22:52 UTC
