### ISSUE TITLE
maybe_connect_more_peers suddenly finishes

### ISSUE THREAD

**Issue by lithp** [ethereum/trinity#1377] opened 2019-12-10 05:59 UTC
* Trinity version: 0.1.0-alpha.32 

### What is wrong?

While running a sync, `trinity --sync-mode=full`, with my Trinity with a custom-built database, everything seemed to be going normally, until I got to the last line of this dump:

```
   DEBUG  2019-12-09 19:13:54,379           ETHPeerPool  Could not complete handshake with <Node(0x9a78a43244f76a6a7f9447f3e695ed08c3dc93d405c99017035b99cbab1c4d136c749124edb4b05aedc72d38d6361b268681672cd7a27118
d488db468abdfec9@134.119.207.243:30303)>: HandshakeFailureTooManyPeers('Peer disconnected because it is already full')                                                                                             
   DEBUG  2019-12-09 19:13:54,389     ConnectionTracker  <Node(0x306d72@163.172.53.103)> will not be retried for 2m48s because HandshakeFailureTooManyPeers                                                        
   DEBUG  2019-12-09 19:13:54,397     ConnectionTracker  <Node(0x9a78a4@134.119.207.243)> will not be retried for 2m48s because HandshakeFailureTooManyPeers                                                       
   DEBUG  2019-12-09 19:13:54,520           ETHPeerPool  Could not complete handshake with <Node(0x5cb587a22c3894510ea7364c7cc3c99af5a6009464ddb75ccdcaab682219799e9d717416adea84aae7cb96ff7c0af557d0bf5331eaab0f50
44d57151b0b6bf03@148.251.88.252:32309)>: WrongNetworkFailure('<Node(0x5cb587@148.251.88.252)> network (323138) does not match ours (1), disconnecting')                                                            
   DEBUG  2019-12-09 19:13:54,535     ConnectionTracker  <Node(0x5cb587@148.251.88.252)> will not be retried for 24m28s because WrongNetworkFailure                                                                
   DEBUG  2019-12-09 19:13:54,552           ETHPeerPool  Could not complete handshake with <Node(0x7cd61e51489d94e23d352da1324c8af82b4f1402177c04f7f5e71d0400578342c7cb0192063e7ec630fbd90f50f2f005539089c7383df275
30236f8ddb226208@207.180.248.207:30696)>: WrongNetworkFailure('<Node(0x7cd61e@207.180.248.207)> network (11235813) does not match ours (1), disconnecting')                                                        
   DEBUG  2019-12-09 19:13:54,567     ConnectionTracker  <Node(0x7cd61e@207.180.248.207)> will not be retried for 26m26s because WrongNetworkFailure                                                               
   DEBUG  2019-12-09 19:13:55,864           ETHPeerPool  <coroutine object BasePeerPool.maybe_connect_more_peers at 0x7ffa15da3c48> finished while <trinity.protocol.eth.peer.ETHPeerPool object at 0x7ffa15deb320$
 is still running, terminating as well                                                                                                                                                                             
```

After this point everything shut itself down and syncing stopped. There are no stack traces in the log, or any other indication of something going awry.

**Comment by gsalgado** [comment] 2019-12-10 12:37
Can you reproduce it easily? ISTM this could only happen if we got an `OperationCancelled` exception when getting peer candidates from the backend, which happens over an event bus, so it might be a bug in the trio-based event bus implementation that we started using recently on the discovery service. I can put together a branch to gather more debug info if you're able to reproduce

**Comment by cburgdorf** [comment] 2020-05-25 14:02
The code base has changed quite a bit since this was reported and I think this may have been a temporary issue that has been addressed already. I'm going to close this for now.

**Closed by cburgdorf** 2020-05-25 14:02 UTC
