### ISSUE TITLE
Failure running the docker image

### ISSUE THREAD

**Issue by holiman** [ethereum/trinity#611] opened 2019-05-15 11:54 UTC
* Trinity version: Trinity/0.1.0a20/linux/cpython3.6.4
* OS: linux, debian
Docker tag `latest`, which is `5a8715ad3fb6` (five months old)

### What is wrong?

Tried following the commands at https://trinity-client.readthedocs.io/en/latest/quickstart.html#running-trinity

Got this
```
user@dockervm:~$ docker run --network host -it ethereum/trinity
    INFO  05-15 11:51:08               trinity  
      ______     _       _ __       
     /_  __/____(_)___  (_) /___  __
      / / / ___/ / __ \/ / __/ / / /
     / / / /  / / / / / / /_/ /_/ / 
    /_/ /_/  /_/_/ /_/_/\__/\__, /  
                           /____/   
    INFO  05-15 11:51:08               trinity  Started main process (pid=1)
    INFO  05-15 11:51:08               trinity  Trinity/0.1.0a20/linux/cpython3.6.4
    INFO  05-15 11:51:08               trinity  Trinity DEBUG log file is created at /root/.local/share/trinity/mainnet/logs/trinity.log
/usr/local/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
    INFO  05-15 11:51:09               trinity  Started DB server process (pid=12)
   ERROR  05-15 11:51:19               trinity  Timeout waiting for database to start.  Exiting...
    INFO  05-15 11:51:19               trinity  Sent SIGINT to process 12, waiting 10 seconds for it to terminate
Process DB:
Traceback (most recent call last):
  File "/usr/src/app/eth/db/header.py", line 146, in _get_canonical_head
    canonical_head_hash = db[SchemaV1.make_canonical_head_hash_lookup_key()]
  File "/usr/src/app/eth/db/backends/level.py", line 54, in __getitem__
    raise KeyError(key)
KeyError: b'v1:canonical_head_hash'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/trinity/initialization.py", line 106, in initialize_database
    chaindb.get_canonical_head()
  File "/usr/src/app/eth/db/header.py", line 141, in get_canonical_head
    return self._get_canonical_head(self.db)
  File "/usr/src/app/eth/db/header.py", line 148, in _get_canonical_head
    raise CanonicalHeadNotFound("No canonical head set for this chain")
eth.exceptions.CanonicalHeadNotFound: No canonical head set for this chain

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/trinity/utils/profiling.py", line 31, in inner
    return fn(*args, **kwargs)
  File "/usr/src/app/trinity/utils/logging.py", line 161, in inner
    return fn(*args, **inner_kwargs)
  File "/usr/src/app/trinity/bootstrap.py", line 234, in run_database_process
    manager = get_chaindb_manager(trinity_config, base_db)
  File "/usr/src/app/trinity/db/manager.py", line 27, in get_chaindb_manager
    initialize_database(chain_config, chaindb, base_db)
  File "/usr/src/app/trinity/initialization.py", line 108, in initialize_database
    chain_config.initialize_chain(base_db)
  File "/usr/src/app/trinity/config.py", line 177, in initialize_chain
    genesis_state=genesis_state,
  File "/usr/src/app/eth/chains/base.py", line 412, in from_genesis
    account_db.persist()
  File "/usr/src/app/eth/db/account.py", line 416, in persist
    self.make_state_root()
  File "/usr/src/app/eth/db/account.py", line 412, in make_state_root
    self._journaltrie.persist()
  File "/usr/src/app/eth/db/journal.py", line 257, in persist
    self.commit(self.journal.root_changeset_id)
  File "/usr/src/app/eth/db/journal.py", line 242, in commit
    self.wrapped_db[key] = value
  File "/usr/src/app/eth/db/cache.py", line 26, in __setitem__
    self._db[key] = value
  File "/usr/src/app/eth/db/keymap.py", line 31, in __setitem__
    self._db[mapped_key] = val
  File "/usr/local/lib/python3.6/site-packages/trie/hexary.py", line 436, in __setitem__
    return self.set(key, value)
  File "/usr/local/lib/python3.6/site-packages/trie/hexary.py", line 96, in set
    new_node = self._set(root_node, trie_key, value)
  File "/usr/local/lib/python3.6/site-packages/trie/hexary.py", line 112, in _set
    return self._set_branch_node(node, trie_key, value)
  File "/usr/local/lib/python3.6/site-packages/trie/hexary.py", line 343, in _set_branch_node
    new_node = self._set(sub_node, trie_key[1:], value)
  File "/usr/local/lib/python3.6/site-packages/trie/hexary.py", line 112, in _set
    return self._set_branch_node(node, trie_key, value)
  File "/usr/local/lib/python3.6/site-packages/trie/hexary.py", line 343, in _set_branch_node
    new_node = self._set(sub_node, trie_key[1:], value)
  File "/usr/local/lib/python3.6/site-packages/trie/hexary.py", line 112, in _set
    return self._set_branch_node(node, trie_key, value)
  File "/usr/local/lib/python3.6/site-packages/trie/hexary.py", line 343, in _set_branch_node
    new_node = self._set(sub_node, trie_key[1:], value)
  File "/usr/local/lib/python3.6/site-packages/trie/hexary.py", line 100, in _set
    self._prune_node(node)
  File "/usr/local/lib/python3.6/site-packages/trie/hexary.py", line 238, in _prune_node
    key, value = self._node_to_db_mapping(node)
  File "/usr/local/lib/python3.6/site-packages/trie/hexary.py", line 209, in _node_to_db_mapping
    return self._cached_create_node_to_db_mapping(tuplify(node))
  File "/usr/local/lib/python3.6/site-packages/trie/hexary.py", line 217, in _cached_create_node_to_db_mapping
    return self._create_node_to_db_mapping(node)
  File "/usr/local/lib/python3.6/site-packages/trie/hexary.py", line 223, in _create_node_to_db_mapping
    encoded_node = encode_raw(node)
  File "/usr/local/lib/python3.6/site-packages/rlp/codec.py", line 88, in encode_raw
    prefix = length_prefix(len(payload), prefix_offset)
  File "/usr/local/lib/python3.6/site-packages/rlp/codec.py", line 109, in length_prefix
    return ALL_BYTES[offset + 56 - 1 + len(length_string)] + length_string
KeyboardInterrupt
    INFO  05-15 11:51:19               trinity  Process 12 has already terminated
usage: trinity [-h]
trinity: error: Timed out waiting for database start
```

**Comment by cburgdorf** [comment] 2019-05-15 13:31
Thanks for reporting Martin. Our docker releases are still managed manually which means they are often out of sync with the actual version :sweat_smile: Not sure why this one is entirely broken. I'm going to look into this and make sure to get the most recent release out.

**Comment by cburgdorf** [comment] 2019-05-15 13:36
I can confirm that I'm also getting this error. The irony is that we actually have a CI job now that [ensures our docker builds work](https://github.com/ethereum/trinity/commit/1b2e9fb318bb1c4b997580ef22b2614ac4c1d39f) but it just happens that we haven't pushed a working version into the docker registry yet. :)

**Comment by cburgdorf** [comment] 2019-05-15 14:36
I just pushed a new image to `trinity:latest`. Notice that normally `latest` just points to the *latest* version but this time points to the actual latest version from `master` instead. 

I went that way because:

1. There were fixes to the docker file that were not yet in the latest Trinity release so I had to do at least some modifications
2. Trinity is still in alpha so I'm not sending people down a rocky path who expected a comfortable, stable ride :)

I've tested the released image and it works for me. Closing this, feel free to reopen if you happen to run into any trouble. Thanks again for reporting!

**Closed by cburgdorf** 2019-05-15 14:36 UTC
