### ISSUE TITLE
flaky fixture eth_peer_and_remote raised a WrongGenesisFailure

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1059] opened 2019-09-05 00:12 UTC
Happened on https://github.com/ethereum/trinity/pull/1045 once, but a re-run made it go away.

### What is wrong?

```
_ ERROR at setup of test_eth_peer_get_block_bodies_round_trip_with_empty_response _
[gw2] linux -- Python 3.6.9 /home/circleci/repo/.tox/py36-eth1-core/bin/python

    @pytest.fixture
    async def eth_peer_and_remote():
>       async with ETHPeerPairFactory() as (peer, remote):


tests/core/p2p-proto/test_peer_block_body_validator_api.py:78: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.tox/py36-eth1-core/lib/python3.6/site-packages/async_generator/_util.py:34: in __aenter__
    return await self._agen.asend(None)
p2p/tools/factories/peer.py:72: in PeerPairFactory
    async with connection_pair as (alice_connection, bob_connection):
.tox/py36-eth1-core/lib/python3.6/site-packages/async_generator/_util.py:34: in __aenter__
    return await self._agen.asend(None)
p2p/tools/factories/connection.py:79: in ConnectionPairFactory
    cancel_token,
p2p/handshake.py:272: in negotiate_protocol_handshakes
    in zip(selected_handshakers, selected_protocols)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <trinity.protocol.eth.handshaker.ETHHandshaker object at 0x7f9c30430fd0>
multiplexer = <Multiplexer[p2p:5,eth:63]>, protocol = (eth, 63)

    async def do_handshake(self,
                           multiplexer: MultiplexerAPI,
                           protocol: ProtocolAPI) -> ETHHandshakeReceipt:
        """Perform the handshake for the sub-protocol agreed with the remote peer.
    
            Raises HandshakeFailure if the handshake is not successful.
            """
        protocol = cast(ETHProtocol, protocol)
        protocol.send_handshake(self.handshake_params)
    
        async for cmd, msg in multiplexer.stream_protocol_messages(protocol):
            if not isinstance(cmd, Status):
                raise HandshakeFailure(f"Expected a ETH Status msg, got {cmd}, disconnecting")
    
            msg = cast(Dict[str, Any], msg)
    
            remote_params = ETHHandshakeParams(
                version=msg['protocol_version'],
                network_id=msg['network_id'],
                total_difficulty=msg['td'],
                head_hash=msg['best_hash'],
                genesis_hash=msg['genesis_hash'],
            )
            receipt = ETHHandshakeReceipt(protocol, remote_params)
    
            if receipt.handshake_params.network_id != self.handshake_params.network_id:
                raise WrongNetworkFailure(
                    f"{multiplexer.remote} network "
                    f"({receipt.handshake_params.network_id}) does not match ours "
                    f"({self.handshake_params.network_id}), disconnecting"
                )
    
            if receipt.handshake_params.genesis_hash != self.handshake_params.genesis_hash:
                raise WrongGenesisFailure(
>                   f"{multiplexer.remote} genesis "
                    f"({encode_hex(receipt.handshake_params.genesis_hash)}) does "
                    f"not match ours ({encode_hex(self.handshake_params.genesis_hash)}), "
                    f"disconnecting"
                )
E               trinity.exceptions.WrongGenesisFailure: <Node(0xc182@10.0.0.58)> genesis (0x3cf7fa8dfebc5d304e475fbc7bed2278f511c6ccbee5b8ebecbd9594ca39a323) does not match ours (0x8d15c5a2e08bae56eb88503b76cff5e8ff70c41a6bbc7fd1e012c47e97e389da), disconnecting

cmd        = <trinity.protocol.eth.commands.Status object at 0x7f9c332ad160>
msg        = {'best_hash': b'<\xf7\xfa\x8d\xfe\xbc]0NG_\xbc{\xed"x\xf5\x11\xc6\xcc\xbe\xe5\xb8\xeb\xec\xbd\x95\x94\xca9\xa3#', 'gen...G_\xbc{\xed"x\xf5\x11\xc6\xcc\xbe\xe5\xb8\xeb\xec\xbd\x95\x94\xca9\xa3#', 'network_id': 1, 'protocol_version': 63, ...}
multiplexer = <Multiplexer[p2p:5,eth:63]>
protocol   = (eth, 63)
receipt    = <trinity.protocol.eth.handshaker.ETHHandshakeReceipt object at 0x7f9c3057dc50>
remote_params = ETHHandshakeParams(head_hash=b'<\xf7\xfa\x8d\xfe\xbc]0NG_\xbc{\xed"x\xf5\x11\xc6\xcc\xbe\xe5\xb8\xeb\xec\xbd\x95\x94\x...G_\xbc{\xed"x\xf5\x11\xc6\xcc\xbe\xe5\xb8\xeb\xec\xbd\x95\x94\xca9\xa3#', network_id=1, total_difficulty=1, version=63)
self       = <trinity.protocol.eth.handshaker.ETHHandshaker object at 0x7f9c30430fd0>

trinity/protocol/eth/handshaker.py:67: WrongGenesisFailure
```

### How can it be fixed

:man_shrugging:

**Comment by pipermerriam** [comment] 2019-09-05 16:45
duplicate of https://github.com/ethereum/trinity/issues/996

**Closed by pipermerriam** 2019-09-05 16:45 UTC
