### ISSUE TITLE
Spurious failure of `test_controle_client_disconnect[make_p2pd_pair_unix-True]`

### ISSUE THREAD

**Issue by lithp** [ethereum/trinity#560] opened 2019-04-30 08:04 UTC
Here's the Circle CI output: https://circleci.com/gh/ethereum/trinity/29834

After I re-ran the tests this one worked.

Output:

```python
__________ test_controle_client_disconnect[make_p2pd_pair_unix-True] ___________
[gw0] linux -- Python 3.7.3 /home/circleci/project/.tox/py37-libp2p/bin/python

peer_id_random = <PeerID cgpsyWgH>
p2pds = [DaemonTuple(daemon=<p2pclient.test_p2pclient_integration.Daemon object at 0x7f4b2ba9a5c0>, client=<libp2p.p2pclient.p...40>, control=<libp2p.p2pclient.p2pclient.ControlClient object at 0x7f4b2ba9aac8>, connmgr=None, dht=None, pubsub=None)]

    @pytest.mark.parametrize(
        'enable_control',
        (True,),
    )
    @pytest.mark.asyncio
    async def test_controle_client_disconnect(peer_id_random, p2pds):
        c0, c1 = p2pds[0].control, p2pds[1].control
        # test case: disconnect a peer without connections
        await c1.disconnect(peer_id_random)
        # test case: disconnect
        peer_id_0, _ = await c0.identify()
        await connect_safe(p2pds[0], p2pds[1])
        assert len(await c0.list_peers()) == 1
        assert len(await c1.list_peers()) == 1
        await c1.disconnect(peer_id_0)
>       assert len(await c0.list_peers()) == 0
E       assert 1 == 0
E        +  where 1 = len((<PeerInfo peer_id=<PeerID fA7Pg5iE> addrs=[<Multiaddr /ip4/172.28.0.3/tcp/44720>]>,))

_          = (<Multiaddr /p2p-circuit>, <Multiaddr /ip4/127.0.0.1/tcp/35897>, <Multiaddr /ip4/172.28.0.3/tcp/35897>)
c0         = <libp2p.p2pclient.p2pclient.ControlClient object at 0x7f4b2ba9a0f0>
c1         = <libp2p.p2pclient.p2pclient.ControlClient object at 0x7f4b2ba9a668>
p2pds      = [DaemonTuple(daemon=<p2pclient.test_p2pclient_integration.Daemon object at 0x7f4b2ba9a5c0>, client=<libp2p.p2pclient.p...40>, control=<libp2p.p2pclient.p2pclient.ControlClient object at 0x7f4b2ba9aac8>, connmgr=None, dht=None, pubsub=None)]
peer_id_0  = <PeerID SaBaUcjE>
peer_id_random = <PeerID cgpsyWgH>

tests/libp2p/p2pclient/test_p2pclient_integration.py:430: AssertionError
```

**Comment by pipermerriam** [comment] 2019-04-30 13:22
Yes, this failure happens **very** regularly.

**Comment by pipermerriam** [comment] 2019-04-30 13:26
@mhchia do you have any thoughts on this?

**Comment by mhchia** [comment] 2019-04-30 14:43
Sorry for this kind of failure again. I am just starting to investigate it. Sadly, I couldn't reproduce this error in my local machine. I'm still trying to reproduce it. I will check through the Go codebase further. After, I will revisit all tests in the p2pclient, and add necessary fixes to prevent this kind of failure from happening in the future.

@pipermerriam 
Question: I suspect I will probably still need to add something similar to `connect_safe` to the tests, which calls `try_until_success` to poll the result and fails if the time is out, to mitigate this issue. Does it sound reasonable to you?

**Comment by ralexstokes** [comment] 2019-05-01 00:32
i was determined to see how we can fix this -- but have immediately run into an issue w/ the client daemon https://github.com/libp2p/go-libp2p-daemon/issues/122

given that this causes external problems via CI failure -- i would suggest we remove this batch of tests from the CI flow for now.

any opposition?

**Comment by pipermerriam** [comment] 2019-05-01 13:34
Excluding from CI with a tracking issue is acceptable to me.

**Comment by ralexstokes** [comment] 2019-09-05 01:40
closing as we are no longer using the client/daemon configuration for our `libp2p` solution

**Closed by ralexstokes** 2019-09-05 01:40 UTC
