### ISSUE TITLE
"mix hash mismatch" on valid headers

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#340] opened 2019-03-01 00:50 UTC
### What is wrong?

Fairly regularly, we get proof-of-work seal validation errors, like "mix hash mismatch: ...". Unfortunately, it appears that the "expected" mix hash appears to be wrong: it doesn't match the mix hash of the blocks in etherscan, for example.

Nothing has changed in PoW for quite a while, so it seems we're exercising it in a new way that's causing problems.

Some options:
- `pyethash` may not like being called from multiple threads/processes
- there may be something funky about how caching works

### How can it be fixed

Figure out which is the real problem and fix that one :man_shrugging:

**Comment by carver** [comment] 2019-03-01 01:08
I wasn't able to reproduce any problems with a test like:

```py
def test_mining_tools_proof_of_work_mining(base_vm_class):
    vm_class = type(base_vm_class.__name__, (POWMiningMixin, base_vm_class), {})

    class ChainClass(MiningChain):
        vm_configuration = (
            (0, vm_class),
        )
        
    chain = genesis(ChainClass)

    blocks = [chain.mine_block() for _ in range(10)] 
    
    def check(): 
        block = random.choice(blocks) 
        check_pow(
            block.number,
            block.header.mining_hash,
            block.header.mix_hash,
            block.header.nonce,
            block.header.difficulty,
        )
         
    import threading 
    threads = [threading.Thread(target=check) for _ in range(10000)]
    for t in threads:
        t.start()
    for t in threads:
        t.join()
```

**Comment by carver** [comment] 2019-03-01 05:44
I thought maybe something wacky was happening with the cache, so I grabbed one header out of each of the first 40 epochs. (the cache is only 10 epochs) Then I ran the same test as above, but randomly choosing one of the 40 in each thread. It took 80 minutes (!) to run, I guess because I was really thrashing the cache. Still couldn't trigger any PoW validation errors.

Next up is to update the debug error logs to print out the serialized header and make sure we're running the validation on the correct values. Maybe even to retry it after the first failure to see if it really is some kind of heisenbug.

**Comment by pipermerriam** [comment] 2019-03-01 06:38
maybe try also installing pawel's new ethhash library and trying to see if both agree (assuming you can configure them to not use the same cache/DAGs)

**Comment by carver** [comment] 2019-03-11 21:36
Not surprisingly, the cache is the problem, and not the underlying library. I still haven't figured out *why* the cache goes bad, but I have confirmed that it is sending the **wrong epoch cache** to `hashimoto_light`. Investigating further...

**Comment by carver** [comment] 2019-03-11 22:23
Fix will go into py-evm, so I'll leave this open until that's released and upgraded in trinity's setup.

**Comment by veox** [comment] 2019-04-14 12:49
FTR this got closed automatically due to how https://github.com/ethereum/py-evm/pull/1732 was worded. The issue is still present.

**Comment by carver** [comment] 2019-04-15 19:31
@veox when you say the problem is still present on master, you mean `trinity` master with unmodified py-evm, right? It should be fixed if you install the py-evm master in your trinity venv.

**Comment by veox** [comment] 2019-04-16 10:38
@carver Yes, that's what I did to bypass the issue until a tagged release is available. ^_^

**Comment by carver** [comment] 2019-04-16 16:20
> @carver Yes, that's what I did to bypass the issue until a tagged release is available. ^_^

The next one will happen soon, hopefully! :)

**Comment by cburgdorf** [comment] 2019-07-09 10:08
We had two more Py-EVM upgrades since then, meaning this landed already.

**Closed by cburgdorf** 2019-07-09 10:08 UTC
