### ISSUE TITLE
Timeout error during header backfill

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#1837] opened 2020-07-04 02:28 UTC
Latest `master` @ bcb4a771

### What is wrong?

This crashed my trinity node.

```python
   ERROR  2020-07-03 20:09:02,019        SkeletonSyncer  Unknown error when getting headers
Traceback (most recent call last):
  File "/home/piper/projects/trinity/p2p/exchange/candidate_stream.py", line 81, in payload_candidates
    timeout=total_timeout * NUM_QUEUED_REQUESTS,
  File "/home/piper/.pyenv/versions/3.7.3/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/piper/projects/trinity/trinity/sync/common/headers.py", line 818, in _request_headers
    return await peer.chain_api.get_block_headers(start_at, length, skip=0, reverse=False)
  File "/home/piper/projects/trinity/trinity/protocol/eth/exchanges.py", line 89, in __call__
    timeout,
  File "/home/piper/projects/trinity/p2p/exchange/exchange.py", line 70, in get_result
    timeout,
  File "/home/piper/projects/trinity/p2p/exchange/manager.py", line 59, in get_result
    async for payload in stream.payload_candidates(request, tracker, timeout=timeout):
  File "/home/piper/projects/trinity/p2p/exchange/candidate_stream.py", line 85, in payload_candidates
    f"Timed out waiting for {self.response_cmd_name} request lock "
p2p.exceptions.ConnectionBusy: Timed out waiting for BlockHeadersV65 request lock or connection: Connection-<Session <Node(0x871124@167.99.114.248)> b9691d64-2c76-4a29-9604-e704a5b97421>
```

### How can it be fixed

Looks like an exception that just needs to be handled, however I'm not 100% sure on that.

**Comment by cburgdorf** [comment] 2020-07-08 08:25
Closing as duplicate of #1797 which has some discussion

**Closed by cburgdorf** 2020-07-08 08:25 UTC
